apiVersion: v1
kind: Service
metadata:
  name: {{ template "mperf.fullname" . }}
  labels:
    app: mperf
spec:
  publishNotReadyAddresses: true
  clusterIP: None  
  ports:
    - port: 9999
      name: http1
    - port: 10000
      name: http2
  selector:
    app: mperf
